# Generated by Django 3.1.3 on 2020-11-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_shop', '0002_auto_20201107_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
