# Generated by Django 3.1.3 on 2020-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_shop", "0005_auto_20201108_0631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.FloatField(null=True),
        ),
    ]
