# Generated by Django 3.1.3 on 2020-11-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('product_shop', '0006_auto_20201108_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
